### ISSUE TITLE
set background color when user enter pin

### ISSUE THREAD

**Issue by amirh3n** [xamous/react-native-smooth-pincode-input#13]
Hello,
i want to set baclground color when user entred the pin

**Comment by retyui** [comment]
@amirh3n 


Thanks for reporting and you can also use better implementation with better maintainability:  [https://github.com/retyui/react-native-confirmation-code-field](https://bit.ly/2xfsRem)

|   |   |
|---|---|
| [![react-native-confirmation-code-field animated example](https://media.giphy.com/media/huJrqF0YRrNJBTwUmz/giphy.gif)](examples/DemoCodeField/src/AnimatedExample) | [![react-native-confirmation-code-field mask example](https://media.giphy.com/media/L4HHvT9Rwdlcdj59np/giphy.gif)](examples/DemoCodeField/src/MaskExample) [![react-native-confirmation-code-field underline example](https://media.giphy.com/media/XEazF64IwELNV8wZge/giphy.gif)](examples/DemoCodeField/src/UnderlineExample) [![react-native-confirmation-code-field basic example](https://media.giphy.com/media/WT4NHiw3XM0GWbjstc/giphy.gif)](examples/DemoCodeField/src/BasicExample) |
