### ISSUE TITLE
Override animations

### ISSUE THREAD

**Issue by matt-dalton** [xamous/react-native-smooth-pincode-input#14]
Is it possible to override the default animations in any way? Even simple stuff like turn them off/slow them down etc?

**Comment by jacek213** [comment]
bump, could use a prop to disable bouncing animation

**Comment by tallytarik** [comment]
+1

Great module, would be awesome to be able to customise the animations.

**Comment by jacek213** [comment]
@xamous are u willing to accept a PR for this?

**Comment by xamous** [comment]
> @xamous are u willing to accept a PR for this?

Sure :)
I’m just too busy at work recently. PRs are welcome. Thanks to all contributors.

**Comment by rickysullivan** [comment]
Yo @xamous. Any chance you can review #38?
