### ISSUE TITLE
autoFocus not working for my code

### ISSUE THREAD

**Issue by NguyenPhatBG** [xamous/react-native-smooth-pincode-input#18]
<SmoothPinCodeInput
                                placeholder="*"
                                cellStyle={{
                                    borderBottomWidth: 2,
                                    borderColor: 'gray'
                                }}
                                cellStyleFocused={{
                                    borderColor: 'black'
                                }}
                                textStyle={{
                                    fontSize: 24,
                                    color: 'salmon'
                                }}
                                textStyleFocused={{
                                    color: 'crimson'
                                }}
                                value={this.state.email_confirm}
                                autoFocus={true}
                                onTextChange={(email_confirm: string) => this.setState({ email_confirm })}
                                onSubmitEditing={() => this[onVerify]()}
                            />

**Comment by dpchami** [comment]
How did you solve this @NguyenPhatBG
