### ISSUE TITLE
ViewPropTypes' is not supported in 'react-native-web' v12.0 onwards

### ISSUE THREAD

**Issue by markybry** [xamous/react-native-smooth-pincode-input#68]
If you upgrade to RNW 12.0 or greater you can no longer use react native web

Error: ./node_modules/react-native-table-component/components/rows.js
Cannot find module: 'react-native-web/dist/exports/ViewPropTypes'. Make sure this package is installed.

**Comment by alfosua** [comment]
There's any way to use this package with Expo? I'm migrating from a bare-workflow project into an Expo-managed one.

**Comment by markybry** [comment]
I decided make a copy of the component and remove viewproptypes as the repo seems dead and my solution isn't really acceptable for a customisable component.
